import { ZoomParticipant } from "./interfaces";

export const sampleParticipants: ZoomParticipant[] = [
  // {
  //   audio: 'computer',
  //   bVideoOn: false,
  //   displayName: 'Teacher',
  //   isHost: true,
  //   isManager: false,
  //   muted: true,
  //   sharePause: undefined,
  //   sharerOn: undefined,
  //   userId: 1,
  // },
  {
    audio: '',
    bVideoOn: false,
    displayName: 'Student 0',
    isHost: true,
    isManager: false,
    muted: true,
    sharePause: undefined,
    sharerOn: undefined,
    userId: 1,
  },
  {
    audio: '',
    bVideoOn: false,
    displayName: 'Student 1',
    isHost: true,
    isManager: false,
    muted: true,
    sharePause: undefined,
    sharerOn: undefined,
    userId: 1,
  },
  {
    audio: '',
    bVideoOn: false,
    displayName: 'Student 2',
    isHost: true,
    isManager: false,
    muted: true,
    sharePause: undefined,
    sharerOn: undefined,
    userId: 1,
  },
  {
    audio: 'computer',
    bVideoOn: false,
    displayName: 'Student 3',
    isHost: true,
    isManager: false,
    muted: true,
    sharePause: undefined,
    sharerOn: undefined,
    userId: 1,
  }
];
